### ISSUE TITLE
About the complementary relationship between Distill-CF and ∞-AE

### ISSUE THREAD

**Issue by Wicknight** [noveens/distill_cf#1]
Thanks for your great work!
I have a question about the complementary relationship between Distill-CF and ∞-AE. You mentioned that Distill-CF and ∞-AE are Distill-CF and ∞-AE in the whole framework.
Does it mean that I can not use other methods instead of ∞-AE in the inner loop to get synthetic data?

**Comment by noveens** [comment]
Hello @Wicknight ,

Thanks for your interest! You're correct -- Distill-CF is *not* limited to using ∞-AE in the inner loop, and other *suitable* methods can work with the overall data distillation framework as well. The major reason for using ∞-AE in the inner loop was to leverage its closed-form optimization for efficient and high-quality distillation.

Does that make sense? Feel free to ask for any further clarifications that you might have :)

**Comment by Wicknight** [comment]
@noveens Thanks for your quick reply!

Then if we use other methods in the inner loop, will there be a significant performance drop? I don't seem to have seen any relevant experimental results in the paper.

**Comment by noveens** [comment]
I don't believe there will be a significant performance drop other than the fact that:

1. It might be difficult to get the optimal data distillation performance (due to more hyperparameters in the inner loop)
2. Due to performing truncated BackProp Through Time (T-BPTT) in the inner loop (since the inner loop doesn't have a closed-form optimization anymore), you'll add a slight amount of bias, which might result in a slightly worse performance

And yes, you're right, there are no experiments like this in the paper since using ∞-AE leads me to both: (1) enjoy best performance, and (2) evade the hyper-parameter tuning in the inner loop as I said above.

Does this help?

**Comment by Wicknight** [comment]
Yes, it helps me! Thanks for your great work and patient reply!
